Gal 22 | Profile page, change password, change avatar
IpratchetI/galaxy_conquerors pull request #14
Opened 2024-01-18 18:15 UTC by IpratchetI

### Какую задачу решаем
Сверстать страницу профиля.

Подключить API смены пароля

Сверстать компонент изменения аватара (необходимо реализовать на макете)

Подключить API для смены аватара пользователя. 

Страница с информацией о пользователе, возможностью загрузить и сменить аватар, изменить пароль (используйте API).

### Скриншоты/видяшка (если есть)
<img width="1430" alt="Снимок экрана 2024-01-18 в 21 08 58" src="https://github.com/IpratchetI/galaxy_conquerors/assets/138199955/5de4ee70-fa85-4f03-a171-0fd086eee0b1">
<img width="1431" alt="Снимок экрана 2024-01-18 в 21 09 26" src="https://github.com/IpratchetI/galaxy_conquerors/assets/138199955/46032429-ab25-4234-a1c7-7ea1e444769a">
<img width="1425" alt="Снимок экрана 2024-01-18 в 21 09 51" src="https://github.com/IpratchetI/galaxy_conquerors/assets/138199955/60a141da-5cb9-44cf-95a0-2d1c50ec51cd">

### TBD (если есть)
доработать отправку и получение Аватара, Данных пользователя, смена пароля.

2024-01-18 19:55 UTC, alexdx0 requested changes

2024-01-18 19:55 UTC, alexdx0 commented on package.json
> +    "axios": "^1.6.5",
Не туда записалась зависимость. Надо в packages\client\package.json. Видимо в корне запустил установку пакета.

2024-01-18 19:55 UTC, alexdx0 commented on packages/client/src/components/Avatar/index.tsx
> +	const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
По идее этот обработчик должен дергать метод сервиса, передавая нужные данные. И уже в методе сервиса выполняется запрос.

2024-01-18 19:55 UTC, alexdx0 commented on packages/client/src/components/ChangePasswordPopup/index.tsx
> +			const response = await axios.put('https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_password', formData, {
Так же: это должен быть метод сервиса

2024-01-18 19:55 UTC, alexdx0 commented on packages/client/src/components/Input/Input.module.scss
> +  // font-size: 1rem;
Забытый комментарий

2024-01-18 19:55 UTC, alexdx0 commented on packages/client/src/pages/Profile/index.module.scss
> +@import '../../style/backgrounds';
Лучше через алиас @

2024-01-18 19:55 UTC, alexdx0 commented on packages/client/src/pages/Profile/index.tsx
> +		const fetchAvatar = async () => {
Нужно вынести в сервисы

2024-01-18 20:03 UTC, egorchh commented on packages/client/src/pages/Profile/index.tsx
> +		document.body.style.overflow = 'hidden';
Для чего задается hidden на body? В React не стоит взаимодейстовать с нативным DOM, если есть другие варианты

2024-01-18 20:16 UTC, IpratchetI commented on package.json
> +    "axios": "^1.6.5",
поправил

2024-01-18 20:18 UTC, IpratchetI commented on packages/client/src/components/Input/Input.module.scss
> +  // font-size: 1rem;
убрал

2024-01-18 21:45 UTC, pira9ha commented on packages/client/src/pages/Profile/index.tsx
> +		document.body.style.overflow = 'hidden';
Блин, я сча запушу ветку и там есть модалка, можно использовать ее)

2024-01-18 21:47 UTC, pira9ha commented on packages/client/src/components/ChangePasswordPopup/index.tsx
> +			const response = await axios.put('https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_password', formData, {
Добавлю только, что базовый путь можно вынести в константы где-нибудь на уровне проекта

2024-01-18 21:49 UTC, pira9ha commented on packages/client/src/components/ChangePasswordPopup/index.module.scss
> +}
Его можно в Spacer

2024-01-19 14:21 UTC, VasiliiOrekhov commented on packages/client/src/services/avatarService.ts
> +			await axios.put('https://ya-praktikum.tech/api/v2/user/profile/avatar', formData, {
https://ya-praktikum.tech/api/v2 можно вынести в BASE_URL

2024-01-19 14:24 UTC, pira9ha commented on packages/client/src/pages/Profile/index.tsx
> +		const fetchAvatar = async () => {
Не совсем поняла как связаны ручки и редакс, если ручки это часть сервиса, а редакс это стейт менеджер, в нем не корректно хранить такие константы или я тебя неправильно поняла?

2024-01-19 18:20 UTC, pira9ha approved these changes

2024-01-19 18:20 UTC, egorchh approved these changes

2024-01-19 18:25 UTC, VasiliiOrekhov approved these changes

2024-01-20 19:13 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀

2024-01-20 19:13 UTC, IvanPeleshok commented on packages/client/src/components/Avatar/index.tsx
> +	useEffect(() => {
Предлагаю на будущее подумать о кастомном хуке с кликом вне

2024-01-20 19:13 UTC, IvanPeleshok commented on packages/client/src/components/ChangePasswordPopup/index.tsx
> +		if (name === 'oldPassword') {
Для удобства валидации можно подумать о том, чтобы использовать Formik + yup
https://www.smashingmagazine.com/2020/10/react-validation-formik-yup/

2024-01-20 19:13 UTC, IvanPeleshok commented on packages/client/src/services/avatarService.ts
> +			await axios.put('https://ya-praktikum.tech/api/v2/user/profile/avatar', formData, {
Можно подумать о том, чтобы вынести url  `https://ya-praktikum.tech` для удобства

2024-01-20 20:15 UTC, merged