[WIP] Gal 18 fomrs validation
IpratchetI/galaxy_conquerors pull request #16
Opened 2024-01-19 17:22 UTC by egorchh

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-01-22 19:00 UTC, IpratchetI approved these changes

2024-01-23 20:21 UTC, pira9ha requested changes

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Есть еще форма отправки сообщения в топик и форма создания топика, минимальную валидацию, но туда тоже можно добавить

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Login/index.module.scss
> +  @include login-background;
Насколько помню, этот фон не только у логина, может имя все-таки другое?

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Login/index.tsx
> +			<Spacer direction="column" gap="12" fullHeight>
А зачем еще одна обертка? Мне кажется, что уже проще было добавить возможность тег передавать в Spacer

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Profile/index.tsx
> +						</Spacer>
Как будто имеет смысл в отдельные компоненты, а то сложно читать

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Profile/index.tsx
> +						</form>
Раз обернуто в FormCard, то тег форм уже не нужен

2024-01-23 20:21 UTC, pira9ha commented on packages/client/src/pages/Profile/index.tsx
> +	} = useForm<UserModel>({
[имхо]  UserModel сейчас не конечный вид модели, у него как минимум должен быть айдишник и не должно быть пароля, лучше от юзера создавать конкретные типы используя его поля в основе

2024-01-23 20:28 UTC, alexdx0 requested changes

2024-01-23 20:28 UTC, alexdx0 commented on packages/client/src/pages/Profile/components/Avatar/index.tsx
> +						// @ts-ignore
А на что он тут ругается? Лучше избегать таких директив.

2024-01-24 17:01 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Заведу задачу для этого

2024-01-24 17:02 UTC, egorchh commented on packages/client/src/pages/Profile/index.tsx
> +						</Spacer>
Заведу задачу на доработки, как откоментил выше, ок?

2024-01-24 17:04 UTC, egorchh commented on packages/client/src/pages/Profile/components/Avatar/index.tsx
> +						// @ts-ignore
Проблема связана с тем, что компонента Input может быть как тег textarea, так и тег input. В идеале тут разнести эти два компонента на отдельные. Эта проблема уже была до моих правок. Могу также включить в таску на доработки

2024-01-24 17:05 UTC, egorchh commented on packages/client/src/pages/Login/index.tsx
> +			<Spacer direction="column" gap="12" fullHeight>
Можно, но тогда нужно будет сразу в куче мест поменять. Гоу это тоже в задачку на доработки

2024-01-24 17:09 UTC, egorchh commented on packages/client/src/pages/Login/index.module.scss
> +  @include login-background;
Гуд, поправлю спасибо

2024-01-24 17:28 UTC, pira9ha commented on packages/client/src/pages/Login/index.tsx
> +			<Spacer direction="column" gap="12" fullHeight>
Да, так даже лучше)

2024-01-24 17:52 UTC, IpratchetI approved these changes

2024-01-24 18:05 UTC, pira9ha commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Подожди, а зачем отдельную задачу? у тебя же текущая задача - 'добавить валидацию'

2024-01-24 18:14 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
А как должна выглядеть валидация сообщения? Для валидации пароля нужен бек, чтобы проверять что пароль не совпадает с предыдущим

2024-01-24 18:30 UTC, pira9ha commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Да как обычная валидация пароля, на беке сделаем такую же, можно взять из предыдущего модуля, там были описаны правила
Не пустая строка как минимум, почему бы нет
Валидацию создания топика можно тож взять какую нибудь базовую не пустая, только буквы, цифры и символы типа точки запятой тд и тп
Не думаю шо кто-то их трогать будет

2024-01-24 18:37 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
океей, сделаю валидацию
Но все таки предлагаю в другой задаче

2024-01-24 18:38 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Сейчас создам задачу на доработки и скину. ПР уже очень большой вышел.

2024-01-24 18:40 UTC, pira9ha commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Ну главное чтоб оно не забылось, другие поля не думая о бэке ты же валидируешь уже

2024-01-24 18:43 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Не забудется, задача уже в to do. Уже сделанная валидация не требует сравнения с предыдущими данными

2024-01-24 18:47 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Хотя может пароль и не нужно сравнивать если мы говорим про клиентский механизм валидации. Ты права

2024-01-24 18:47 UTC, pira9ha commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
Что ты имеешь в виду? Причём тут вообще все это и пароль? Сравнение двух паролей тупо на посимвольное соответствие, любые данные, которые даже уже готовы на беке валидируются, а сейчас ты заполняешь валидацию на клиенте, будет на беке не соотв регулярок то просто поправим - ВОТ ЭТО другая задача)

2024-01-24 18:49 UTC, egorchh commented on packages/client/src/pages/Login/constants/index.ts
> +export const loginInputsConfig: FormField<UserLoginModel>[] = [
ок

2024-01-24 19:06 UTC, pira9ha approved these changes

2024-01-24 19:24 UTC, alexdx0 commented on packages/client/src/pages/Profile/components/Avatar/index.tsx
> +						// @ts-ignore
> Проблема связана с тем, что тег компонента Input может быть как тег textarea, так и input. И TS не понимает какой синтетический эвент в данный момент нужен. В идеале тут разнести эти два компонента на отдельные. Эта проблема уже была до моих правок. Могу также включить в таску на доработки

Да, надо с этим что-то делать. Я за то, чтобы разнести. И да, пожалуйста в задачу на доработку. Может кто еще выскажет свои соображения.

2024-01-24 19:25 UTC, alexdx0 approved these changes

2024-01-24 19:38 UTC, VasiliiOrekhov approved these changes

2024-01-24 20:25 UTC, egorchh commented on packages/client/src/components/Input/index.tsx
> +		}
Спасибо!

2024-01-24 20:29 UTC, merged