Gal 26 | Создать механику игры на Canvas API
IpratchetI/galaxy_conquerors pull request #21
Opened 2024-01-24 14:31 UTC by IpratchetI

### Какую задачу решаем
Реализуем механики игры

### Скриншоты/видяшка (если есть)
<img width="1234" alt="Снимок экрана 2024-01-24 в 17 30 04" src="https://github.com/IpratchetI/galaxy_conquerors/assets/138199955/485bfb66-32b0-42d1-b814-799a7f844f91">

### TBD (если есть)
необходимо поправить логику движения противников

2024-01-24 19:42 UTC, alexdx0 requested changes

2024-01-24 19:42 UTC, alexdx0 commented on packages/client/src/components/AppRouter/constants.ts
> +	game: 'Game',
Все роуты со строчной начинаются. Давай и этот так же сделаем.

2024-01-24 19:42 UTC, alexdx0 commented on packages/client/src/components/AppRouter/constants.ts
> +	leaderboard: 'Leaderboard',
И здесь со строчной)

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/components/AppRouter/AppRouter.tsx
> +import Game from '@pages/Game';
Давай пожалуйста заменим дефолтный экспорт на именованный, все остальные страницы я привел к именованному. (Просто половина была так, половина была так)

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/gameEngine/GameEngine.tsx
> +		for (let i = 0; i < 9; i++) {
`i < 9` Кол-во врагов всега будет одинаковым, возможно стоит сразу заложиться на изменение кол-ва. Хотя наверное это будет лишним переусложнением на данном этапе. Что думаешь?

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/gameEngine/GameEngine.tsx
> +			const enemy = new Enemy(90 + i * 100 + horizontalOffset, 150 + verticalSpacing, 50, 50, 50); //последнее значение скорость движения
Кмк, было бы классно принимать не цепочку аргументов в классы, а объект формата ключ-значение. Тогда в любом месте, где класс используется было бы видно что подразумевается под данными которые передаем

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/gameEngine/GameEngine.tsx
> +		this.ship.update(this.canvas.width);
имхо, функция update передвигает сущности, может более правильно ее будет назвать move?

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/gameEngine/GameEngine.tsx
> +					bullet.x < enemy.x + enemy.width &&
Подскажи пожалуйста, почему во всех условиях не `<=` и `>=`, а `<` и `>`? На первый взгляд кажется что попадание должно регаться пиксель в пиксель. Это не замечание, просто интересно

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/pages/Game/index.tsx
> +		const canvas = canvasRef.current!;
Не крит, но лучше не юзать !. Лучше обернуть в условие `if (canvasRef?.current) {...`

2024-01-24 20:52 UTC, egorchh commented on packages/client/src/pages/LeaderBoard/index.module.scss
> +  // .button {
Забыл удалить?

2024-01-24 20:53 UTC, egorchh commented
Очень крутая работа проделана. Все так четенько по классам разложено. 👍🏻

2024-01-24 22:29 UTC, pira9ha commented on packages/client/src/gameEngine/GameEngine.tsx
> +		this.ship.update(this.canvas.width);
Или updatePosition может?

2024-01-24 22:30 UTC, pira9ha commented on packages/client/src/pages/Game/index.tsx
> +		const canvas = canvasRef.current!;
Ставить опц оператор после ref необязательно, не заданным может быть именно значение current

2024-01-24 22:32 UTC, pira9ha commented on packages/client/src/gameEngine/GameEngine.tsx
> +			const enemy = new Enemy(90 + i * 100 + horizontalOffset, 150 + verticalSpacing, 50, 50, 50); //последнее значение скорость движения
От себя тут же добавлю, что лучше от магических чисел избавиться

2024-01-25 07:24 UTC, VasiliiOrekhov commented on packages/client/src/gameEngine/GameEngine.tsx
> +			const enemy = new Enemy(90 + i * 100 + horizontalOffset, 150 + verticalSpacing, 50, 50, 50); //последнее значение скорость движения
правила в линт нужно добавить

2024-01-25 08:29 UTC, IpratchetI commented on packages/client/src/components/AppRouter/constants.ts
> +	game: 'Game',
исправлено

2024-01-25 08:29 UTC, IpratchetI commented on packages/client/src/components/AppRouter/constants.ts
> +	leaderboard: 'Leaderboard',
исправлено

2024-01-25 09:44 UTC, IpratchetI commented on packages/client/src/components/AppRouter/AppRouter.tsx
> +import Game from '@pages/Game';
поправил

2024-01-25 10:11 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +			const enemy = new Enemy(90 + i * 100 + horizontalOffset, 150 + verticalSpacing, 50, 50, 50); //последнее значение скорость движения
исправил на ключ-значение

2024-01-25 10:13 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +		this.ship.update(this.canvas.width);
переименовал в moveShip.
updatePosition не подойдет, у нас есть и другие отрисованные элементы, которые меняет расположение

2024-01-25 10:25 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +					bullet.x < enemy.x + enemy.width &&
На случай если объект окажется внутри, это скорее чтобы обезопасить себя

2024-01-25 10:29 UTC, IpratchetI commented on packages/client/src/pages/Game/index.tsx
> +		const canvas = canvasRef.current!;
ок

2024-01-25 10:29 UTC, IpratchetI commented on packages/client/src/pages/LeaderBoard/index.module.scss
> +  // .button {
убрал

2024-01-25 11:58 UTC, egorchh approved these changes

2024-01-25 12:00 UTC, egorchh commented
У тебя в добавлено новое изображение фона, но на скрине в описании ПР используется уже существующий. Нам нужен еще один фон? Или ты не тот заиспользовал/устаревший скрин? Давай сожмем картинку фона, сможем выиграть немного килобайт.

2024-01-25 12:04 UTC, IpratchetI commented
фоном буду конкретно заниматься в задаче которая относится к оформлению, это пока временное решение, чтобы весь геймплей не был на белом фоне

2024-01-25 17:21 UTC, alexdx0 approved these changes

2024-01-25 17:29 UTC, VasiliiOrekhov approved these changes

2024-01-25 21:13 UTC, kate-lozovaya reviewed
В целом все нормально, но лучше вынести магические переменные в константы, не везде понятно, что это за числа такие.
Призови меня, как посмотришь и ответишь на комментарии

2024-01-25 21:13 UTC, kate-lozovaya commented on packages/client/src/gameEngine/GameEngine.tsx
> +		this.ship = new Ship({ x: 400, y: 500, width: 50, height: 50 }); //отрисовка корабля
[Предложение]
Тут можно x и y подстраивать под экран, чтобы точно выглядело, как ожидается

2024-01-25 21:13 UTC, kate-lozovaya commented on packages/client/src/gameEngine/GameEngine.tsx
> +		} else if (event.code === 'Space' && Date.now() - this.lastShotTime > 1000) {
[Предложение]
1000 лучше вынести в константу, чтобы можно было ее легко менять

2024-01-25 21:13 UTC, kate-lozovaya commented on packages/client/src/gameEngine/GameEngine.tsx
> +		} else if (event.code === 'Space' && Date.now() - this.lastShotTime > 1000) {
еще мне кажется, что `Date.now() - this.lastShotTime > 1000` больше относится именно к функции `shoot`. Посмотри, может будет удобно, если перенести это условие в нее

2024-01-25 21:13 UTC, kate-lozovaya commented on packages/client/src/gameEngine/GameEngine.tsx
> +		const borderOffset = 100; // Расстояние от границы экрана
Кажется, это те же 100, что и в enemy. Если это так, лучше использовать одну константу

2024-01-26 11:23 UTC, IpratchetI commented on packages/client/src/gameEngine/Ship/Ship.ts
> +	isMovingRight: boolean;
Заменил на одну переменную moveShipDirection

2024-01-26 11:33 UTC, IpratchetI commented on packages/client/src/gameEngine/Ship/Ship.ts
> +		this.speed = 5; //значение скорости движения корабля
согласен, вынес

2024-01-26 11:38 UTC, IpratchetI commented on packages/client/src/gameEngine/Ship/Ship.ts
> +		ctx.fillRect(this.x, canvasHeight - this.height - 50, this.width, this.height);
50 - смещение карабля от нижней границы

2024-01-26 11:47 UTC, IpratchetI commented on packages/client/src/gameEngine/Enemy/Enemy.ts
> +		const reachedRightEdge = allEnemies.some(enemy => enemy.x + enemy.width >= canvasWidth - 100);
Это граница слева и справа. Вынес в константу

2024-01-26 11:51 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +		this.ship = new Ship({ x: 400, y: 500, width: 50, height: 50 }); //отрисовка корабля
переделал

2024-01-26 12:06 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +		} else if (event.code === 'Space' && Date.now() - this.lastShotTime > 1000) {
1000 вынес в константу. 
Date.now() - this.lastShotTime > 1000 перенес в shoot

2024-01-26 12:24 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +		const borderOffset = 100; // Расстояние от границы экрана
вынес оба значения в одну константу в файле constants.ts
думаю он мне пригодится

2024-01-26 13:54 UTC, kate-lozovaya approved these changes
Написала два комментария. Они дублируют комментарии из предыдущей итерации. Поставлю апрув, но лучше доделай )

2024-01-26 14:15 UTC, IpratchetI commented on packages/client/src/gameEngine/Ship/Ship.ts
>  		}
упростил

2024-01-26 14:20 UTC, IpratchetI commented on packages/client/src/gameEngine/GameEngine.tsx
> +		const initialShipY = this.canvas.height - 100; // позиция корабля по вертикали
сделал

2024-01-26 14:23 UTC, merged