Gal 32 | Проработать визуальную часть игры
IpratchetI/galaxy_conquerors pull request #23
Opened 2024-01-29 15:04 UTC by IpratchetI

### Какую задачу решаем
Проработка визуальной части игры:
-элементы заглушки заменены на финальные модели
-добавлены анимации к движущимся объектам
-добавлены анимации на столкновения

### Скриншоты/видяшка (если есть)
<img width="1003" alt="Снимок экрана 2024-01-29 в 18 02 42" src="https://github.com/IpratchetI/galaxy_conquerors/assets/138199955/6a59c80a-e6c8-4c35-a9bb-40808c1f589f">

### TBD (если есть)

2024-01-29 15:57 UTC, egorchh commented on packages/client/src/assets/gameplay/enemy/enemyFrame1.png
Сжимал картинки?

2024-01-29 16:25 UTC, IpratchetI commented on packages/client/src/assets/gameplay/enemy/enemyFrame1.png
они вроде и так не большие, имеет ли смысл еще сжимать?

2024-01-29 20:46 UTC, alexdx0 requested changes

2024-01-29 20:46 UTC, alexdx0 commented on packages/client/src/gameEngine/Enemy/Enemy.ts
> +import enemyFrame1 from '../../assets/gameplay/enemy/enemyFrame1.png';
Можно импортировать через алиасы TS как 
import enemyFrame1 from '@assets/gameplay/enemy/enemyFrame1.png';

2024-01-29 20:46 UTC, alexdx0 commented on packages/client/src/gameEngine/Explosion/Explosion.ts
> +import explosionFrame1 from '../../assets/gameplay/explosion/explosionFrame1.png';
Можно использовать алиасы.

2024-01-29 20:46 UTC, alexdx0 commented on packages/client/src/gameEngine/Explosion/Explosion.ts
> +		this.currentAnimationFrame = (this.currentAnimationFrame + 1) % this.frames.length;
Здесь точно нужно использовать остаток от деления? Не совсем понял логику.

2024-01-29 21:21 UTC, egorchh commented on packages/client/src/assets/gameplay/enemy/enemyFrame1.png
Всегда имеет смысл сжимать, качество главное сильно не ужать

2024-01-29 21:45 UTC, pira9ha approved these changes

2024-01-30 07:29 UTC, VasiliiOrekhov approved these changes

2024-01-30 10:53 UTC, alexdx0 approved these changes

2024-01-30 12:40 UTC, merged