Gal-34/web apis
IpratchetI/galaxy_conquerors pull request #24
Opened 2024-01-30 20:09 UTC by alexdx0

### Какую задачу решаем
Добавлены Web API: Fullscreen API, NotificationAPI

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-01-30 21:57 UTC, pira9ha approved these changes

2024-01-30 21:57 UTC, pira9ha commented on packages/client/src/pages/Main/index.tsx
> +		// TODO здесь должно быть получение данных о новых сообщениях/темах в форуме. пока что временная демонстрационная реализация
На прошлом ревью посоветовали такие тудушки сразу оформлять в задачи

2024-01-30 21:57 UTC, pira9ha commented on packages/client/src/pages/Main/index.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
Если правило отключаешь, то тут либо useCallback не имеет смысла, либо раз у нас стоит ворнинг, то оставить как есть, все не покроешь такими дизейблайми, смысл тогда от правил)

2024-01-30 21:57 UTC, pira9ha commented on packages/client/src/pages/Game/index.tsx
> +				text="&#128470;"
Может лучше картинкой? а то у меня не отображается чет( или подскажите как исправить
<img width="128" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/3439ffd0-a2b9-4d3c-927b-be4798f61eb2">
<img width="331" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/b161e9b8-a592-4c7f-98ba-7e8e1d848672">

2024-01-31 12:26 UTC, IpratchetI requested changes
Анимаций и моделей нет.
Ты не мержился с веткой dev?

2024-01-31 12:26 UTC, IpratchetI commented on packages/client/src/pages/Game/index.tsx
> +				text="&#128470;"
та же история

2024-01-31 12:40 UTC, alexdx0 commented on packages/client/src/pages/Main/index.tsx
> +		// TODO здесь должно быть получение данных о новых сообщениях/темах в форуме. пока что временная демонстрационная реализация
Оставил как коментарий.

2024-01-31 12:41 UTC, alexdx0 commented on packages/client/src/pages/Main/index.tsx
> +		// eslint-disable-next-line react-hooks/exhaustive-deps
Убрал мемоизацию.

2024-01-31 12:46 UTC, pira9ha commented on packages/client/src/pages/Game/index.tsx
> +				text="&#128470;"
Вообще кстати, я только сейчас заметила, но title передавать к теги лучше текстом именно как подпись того, что там есть, если там картинка

2024-01-31 12:49 UTC, alexdx0 commented on packages/client/src/pages/Game/index.tsx
> +				text="&#128470;"
Ого, странно. Это был юникод-символ. Переделал на иконку.

2024-01-31 12:49 UTC, alexdx0 commented
> Анимаций и моделей нет. Ты не мержился с веткой dev?

Проверю, подтяну изменения.

2024-01-31 12:55 UTC, IpratchetI approved these changes

2024-01-31 16:42 UTC, VasiliiOrekhov approved these changes

2024-01-31 21:37 UTC, egorchh commented on packages/client/src/assets/icons/fullscreenButton.svg
Сори, что так поздно смотрю ПР, все замечания не крит: 
Лучше сразу svg сжимать, это экономит процентов 20 от веса картинки. Можно воспользоваться например сервисом https://svgomg.net/. Сжатие, по сути, сделает svg разметку одной строкой

2024-01-31 21:37 UTC, egorchh commented on packages/client/src/hooks/useFullscreen.ts
> +	const keydownHandler = useCallback(
Неправильно использован camelCase в названии функций keyDownHandler и keyUpHandler. Хэндлеры правильней называть следующим образом: 1 - `handle` 2 - Тот объект, который хендлер обрабатывает. В данном случае это `Key` 3 - Действие, которое этот хэндлер обрабатывает `Down`. 

Получается `handleKeyDown`. Еще проблема названия keyDownHandler в том, что в ней нет глагола

2024-01-31 21:37 UTC, egorchh commented on packages/client/src/hooks/useFullscreen.ts
> +		document.addEventListener('keydown', keydownHandler, false);
В addEventListener/removeEventListener 3 аргумент по дефолту `false`, можно сократить запись до такого вида: `document.addEventListener('keydown', keydownHandler);`

2024-01-31 21:45 UTC, egorchh approved these changes

2024-02-01 11:58 UTC, DazzlingFame approved these changes
Привет, хорошая работа! Вижу, что часть комментариев ты поправил ещё в процессе ревью с командой, это очень круто! 
В текущем состоянии работы не заметил критичных замечаний, так что работу принимаю 👍 
Оставил тебе несколько комментариев в коде, они не обязательны к исправлению, но помогут с чистотой и читаемостью кода. Обрати на них внимание перед влитием реквеста 🙏

2024-02-01 11:58 UTC, DazzlingFame commented on packages/client/src/hooks/useFullscreen.ts
> +	const combination = useRef(new Set());
_Не критично, но лучше исправить_

У `KeyboardEvent.key` тип `string`, так что лучше сразу типизировать `Set` как сет строк. Это позволит дальше не использовать каст `x as string` в 29 строке

2024-02-01 11:58 UTC, DazzlingFame commented on packages/client/src/hooks/useFullscreen.ts
> +	const keydownHandler = useCallback(
Согласен, `handleKeyDown` звучит лучше. Это не критично, но если у вас в проекте единый стиль именования, то лучше поправить нейминг

2024-02-01 11:58 UTC, DazzlingFame commented on packages/client/src/hooks/useNotification.ts
> +			}
_Не критично, но лучше исправить_

Тут получилось нагромождение из-за `else if`, можно исправить это и улучшить читаемость

После `return` `else` не нужен, так как код не дойдет до этого места в любом случае

После обработки `granted` предлагаю убрать проверку на `denied` 
`if (Notification.permission !== 'denied')`
и просто запрашивать разрешение для всех состояний кроме `granted`
```suggestion
			if (!('Notification' in window)) {
				return;
			} 
			if (Notification.permission === 'granted') {
				notification.current = createNotification(text);
			} else {
				Notification.requestPermission().then(permission => {
					if (permission === 'granted') {
						notification.current = createNotification(text);
					}
				});
			}
```

2024-02-01 13:10 UTC, alexdx0 commented on packages/client/src/assets/icons/fullscreenButton.svg
Сжал изображение.

2024-02-01 13:15 UTC, alexdx0 commented on packages/client/src/hooks/useFullscreen.ts
> +	const keydownHandler = useCallback(
Исправил нейминг.

2024-02-01 13:16 UTC, alexdx0 commented on packages/client/src/hooks/useFullscreen.ts
> +	const combination = useRef(new Set());
Спасибо, исправил.

2024-02-01 14:31 UTC, alexdx0 commented on packages/client/src/hooks/useNotification.ts
> +			}
В таком случае пользователь будет получать предложение получать уведомления каждый раз при входе в игру, даже если он уже отказался от уведомлений. Мне кажется это нехорошо. Оставлю пока логику такой.

2024-02-01 14:35 UTC, merged