Gal 31/add state start/end game
IpratchetI/galaxy_conquerors pull request #26
Opened 2024-01-31 15:36 UTC by VasiliiOrekhov

### Какую задачу решаем
Добавлены состояния начала и конца игры.
Реализована пауза при нажатии на esc.
Добавлено сохранение очков в стор.

### Скриншоты/видяшка (если есть)
видео в тг
![image](https://github.com/IpratchetI/galaxy_conquerors/assets/116024926/ff6d284e-8783-4f2b-b826-51f9bce516ff)
![image](https://github.com/IpratchetI/galaxy_conquerors/assets/116024926/7db990e6-2e0d-4213-9730-a2d53becc1de)
![image](https://github.com/IpratchetI/galaxy_conquerors/assets/116024926/f12dd491-8ca1-4adb-b794-4e7a52a279a5)

### TBD (если есть)

2024-01-31 18:08 UTC, pira9ha requested changes

2024-01-31 18:08 UTC, pira9ha commented on packages/client/src/pages/Game/index.tsx
> +		const newMaxScore = scoreNow > prevScore.maxScore ? scoreNow : prevScore.maxScore;
можно использовать Math.max

2024-01-31 18:09 UTC, IpratchetI commented
Нужно разрешить конфликты

2024-01-31 18:20 UTC, VasiliiOrekhov commented on packages/client/src/pages/Game/components/BreakGamePopup/index.tsx
> +				</p>
Text не поддерживает перенос, по крайне мере не нашел как его сделать

2024-01-31 19:01 UTC, VasiliiOrekhov commented on packages/client/src/pages/Game/index.tsx
> +		const newMaxScore = scoreNow > prevScore.maxScore ? scoreNow : prevScore.maxScore;
согласен, исправил

2024-01-31 19:02 UTC, VasiliiOrekhov commented on packages/client/src/pages/Game/index.tsx
> +		const prevScore = store.getState().userState.score;
сделал через селектор, не уверен, что это решение лучше тк функция уже не чистая получается

2024-01-31 19:16 UTC, alexdx0 commented on packages/client/src/pages/Game/components/BreakGamePopup/index.tsx
> +				</p>
> Text не поддерживает перенос, по крайне мере не нашел как его сделать

На странице Main есть решение, выглядит так:
`<Text tag="h1" size="xxl" align="center">
					{'Galaxy \n Conquerors'}
				</Text>`

2024-01-31 19:20 UTC, VasiliiOrekhov commented on packages/client/src/pages/Game/components/BreakGamePopup/index.tsx
> +				</p>
спасибо!

2024-01-31 19:30 UTC, alexdx0 requested changes

2024-01-31 19:30 UTC, alexdx0 commented on packages/client/src/gameEngine/GameEngine.ts
> +	private initialEnemySpeed = 1000;
Это точно нужно оставить? Я думал, что только для демонстрации было ускорение движения.

2024-01-31 19:30 UTC, alexdx0 commented on packages/client/src/main.tsx
> -	<React.StrictMode>
Почему был отключен StrictMode?

2024-01-31 19:34 UTC, VasiliiOrekhov commented on packages/client/src/gameEngine/GameEngine.ts
> +	private initialEnemySpeed = 1000;
это случайно запушил

2024-01-31 19:35 UTC, VasiliiOrekhov commented on packages/client/src/main.tsx
> -	<React.StrictMode>
useEffect запускается дважды при монтировании компонента и движок игры некорректно работал

2024-01-31 21:01 UTC, VasiliiOrekhov commented on packages/client/src/constants/routerPaths.ts
пути обратно в итоге все вернул)

2024-02-01 08:35 UTC, IpratchetI approved these changes

2024-02-01 18:30 UTC, DazzlingFame commented
Привет! Допройди командное ревью у @alexdx0 и призови ревьюера ещё раз. Важно сначала полностью пройти процесс ревью от команды.

2024-02-01 18:50 UTC, alexdx0 commented on packages/client/src/main.tsx
> -	<React.StrictMode>
Так и должно быть. Это сделано для выявления "нечистых". Визуально проблем не видел. Лучше его вернуть.

2024-02-01 19:30 UTC, VasiliiOrekhov commented on packages/client/src/main.tsx
> -	<React.StrictMode>
у нас движок запускается в useEffect, со StrictMode получается что дважды, соответственно некорректно работает.

2024-02-02 06:49 UTC, alexdx0 commented on packages/client/src/main.tsx
> -	<React.StrictMode>
Тогда надо уничтожать экземпляр, очищать эффект и создавать новый. Мне так кажется. Надо будет обратить на это внимание в будущем. Ставлю аппрув.

2024-02-02 06:49 UTC, alexdx0 approved these changes

2024-02-02 12:54 UTC, VasiliiOrekhov commented on packages/client/src/pages/Gameover/index.tsx
> +	const lastGameScore = store.getState().userState.score.lastGameScore;
исправил

2024-02-02 13:20 UTC, DazzlingFame approved these changes
Спасибо за правки, реквест принимаю 👍

2024-02-02 15:07 UTC, merged