GAL-29: Service Worker
IpratchetI/galaxy_conquerors pull request #27
Opened 2024-02-03 19:18 UTC by pira9ha

### Какую задачу решаем
Добавить Service Workers - [ссылка на задачу](https://linear.app/galaxyconquerors/issue/GAL-29/6-dobavit-service-workers)

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-02-03 20:41 UTC, alexdx0 requested changes

2024-02-03 20:41 UTC, alexdx0 commented on packages/client/sw.ts
> +const CACHE_NAME = 'cache_v1';
Не критично
Предпочел бы назвать полностью, т.е. ServiceWorker

2024-02-03 20:41 UTC, alexdx0 commented on packages/client/public/icons/icon-128x128.png
Не критично
Предлагаю эти иконки сложить в отдельную папку здесь же, например, MainIcon

2024-02-03 20:57 UTC, pira9ha commented on packages/client/public/icons/icon-128x128.png
Иконки для страниц лежат в assets, не думаю, что в public будут еще какие-то

2024-02-03 20:59 UTC, egorchh approved these changes

2024-02-03 20:59 UTC, egorchh commented on packages/client/public/icons/icon-128x128.png
Тогда наверное лучше назвать папку `favicon`. Фавиконка - это как раз маленькая картинка на вкладке или на рабочем столе десктопа/мобилки

2024-02-03 20:59 UTC, egorchh commented on packages/client/src/app.tsx
> +import { registerServiceWorker } from '@/utils/registerWorker';
Кажется тут не используемый импорт

2024-02-03 21:00 UTC, egorchh commented on packages/client/public/icons/icon-128x128.png
Мало ли

2024-02-03 21:06 UTC, IpratchetI approved these changes

2024-02-04 08:26 UTC, VasiliiOrekhov approved these changes

2024-02-04 09:41 UTC, alexdx0 approved these changes

2024-02-04 12:40 UTC, merged