GAL-35 add MemoryLeaks.md, fix some leaks
IpratchetI/galaxy_conquerors pull request #29
Opened 2024-02-11 17:54 UTC by egorchh

### Какую задачу решаем

Добавил файл memoryleaks.md в docs, в котором описал анализ приложения на утечки памяти

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-02-12 06:42 UTC, alexdx0 requested changes

2024-02-12 06:42 UTC, alexdx0 commented on packages/client/docs/MemoryLeaks.md
> +  - Находимся в главном меню --> делаем скриншот
Скорее snapshot

2024-02-12 18:46 UTC, alexdx0 approved these changes

2024-02-13 14:33 UTC, IpratchetI approved these changes

2024-02-13 15:37 UTC, VasiliiOrekhov approved these changes

2024-02-13 18:02 UTC, IvanPeleshok approved these changes
Проделана качественная работа!

Замечательно, что в ходе реализации задачки удалось найти утечки памяти и исправить кейсы, где это происходило

Отлично оформлен файл с анализом 🚀 

Буду с удовольствием следить за вашим проектов в будущем!

Поздравляю, работа принята!

2024-02-13 19:36 UTC, merged