GAL-47/message-reactions-client
IpratchetI/galaxy_conquerors pull request #39
Opened 2024-03-05 07:31 UTC by alexdx0

### Какую задачу решаем
Добавление реакций на сообщения в темах форума

### Скриншоты/видяшка (если есть)
![image](https://github.com/IpratchetI/galaxy_conquerors/assets/33890200/12e4f666-3e76-459c-9a1d-1a8dcaba39ec)

### TBD (если есть)

2024-03-05 16:24 UTC, IpratchetI approved these changes

2024-03-05 18:03 UTC, egorchh commented on packages/client/src/pages/Topic/components/Reactions/index.tsx
> +	return !Object.keys(props.reactions).length ? null : (
Предлагаю вынести условие в начало компонента следующим образом:

`
if (!Object.keys(props.reactions).length) return null;
`
`return (...`

2024-03-05 18:03 UTC, egorchh commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +	const clickRef = useClickOutside(() => setIsOpen(false));
Зачем прокидывать реф для клика в `Spacer`? Давай просто добавим пропс `onClick`, в `Spacer` же под капотом используется `div`

2024-03-05 18:07 UTC, egorchh commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +	const clickRef = useClickOutside(() => setIsOpen(false));
А, понял для чего, это же чтобы скрывать всплывашку с выбором реакций?

2024-03-05 18:39 UTC, VasiliiOrekhov approved these changes

2024-03-06 17:38 UTC, IvanPeleshok commented on packages/client/src/components/Spacer/index.tsx
> +export const Spacer = forwardRef(function Spacer(props: SpacerProps, ref) {
Предлагаю следующую запись: 
```
export const Spacer = forwardRef(props: SpacerProps, ref) => 
```
Имхо, так немного более читаемо

2024-03-06 17:41 UTC, IvanPeleshok commented on packages/client/src/pages/Topic/components/Reactions/index.tsx
> +	return !Object.keys(props.reactions).length ? null : (
```
return !Object.keys(props.reactions).length
  && ( 
    JSX 
  )

2024-03-06 17:43 UTC, IvanPeleshok commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +										onClick={() => handlerSelectSmile()}>
```
onClick={handlerSelectSmile}>
```
Колбек функции сложно оптимизировать и читать

2024-03-06 17:44 UTC, IvanPeleshok commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +								{smiles.map((smile, i) => (
Предлагаю не сокращать наименование `index`

2024-03-06 17:45 UTC, IvanPeleshok commented on packages/client/src/services/forumService.ts
> +class ForumService {
Супер, что есть моковые данные

2024-03-06 17:47 UTC, IvanPeleshok commented on packages/client/src/store/reducers/forum/forumActionCreator.ts
> +			return await ForumService.getTopicsList();
Конструкция `return await` достаточно плохо читается
Предлагаю следующее:
```
const response =  await ForumService.getTopicsList()
return response

2024-03-06 17:50 UTC, IvanPeleshok requested changes
Отлично реализовали фичу

Есть небольшие замечания, предлагаю поправить

Хорошего дня :)

2024-03-06 18:05 UTC, alexdx0 commented on packages/client/src/components/Spacer/index.tsx
> +export const Spacer = forwardRef(function Spacer(props: SpacerProps, ref) {
Исправлено.

2024-03-06 18:06 UTC, alexdx0 commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +								{smiles.map((smile, i) => (
Исправлено.

2024-03-06 18:08 UTC, alexdx0 commented on packages/client/src/pages/Topic/components/SmileMenu/index.tsx
> +										onClick={() => handlerSelectSmile()}>
Исправлено.

2024-03-06 18:11 UTC, alexdx0 commented on packages/client/src/store/reducers/forum/forumActionCreator.ts
> +			return await ForumService.getTopicsList();
Исправлено.

2024-03-06 19:56 UTC, IvanPeleshok approved these changes
Отлично реализовали фичу
Поздравляю, апрув!
Хорошего дня :)

2024-03-06 19:57 UTC, merged

2024-03-06 19:57 UTC, IvanPeleshok commented on packages/client/src/pages/Topic/components/Reactions/index.tsx
> +	return !Object.keys(props.reactions).length ? null : (
Как вариант, но чаще всего реализуют следующим образом:
```
условие && ( JSX )
```
Если условие не пройдёт, то вернёт undefined, а такое реакт не рендерит