Вёрстка страницы форума
IpratchetI/galaxy_conquerors pull request #4
Opened 2024-01-12 15:53 UTC by pira9ha

### Какую задачу решаем

Ссылка на задачу - [Вёрстка страницы форума](https://linear.app/galaxyconquerors/issue/GAL-17/vyorstka-stranicy-foruma)
К форуму относятся две страницы - главная форума с топиками и открытый топик

### Скриншоты/видяшка (если есть)

<img width="470" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/a32e48c4-84f9-48ca-a59f-f12daf648a0f">

### TBD (если есть)

2024-01-15 06:30 UTC, egorchh commented on package.json
> +    "fix": "lerna run lint:fix && yarn run format",
Давай скрипт `&& yarn run format` добавим в `lint:fix`, чтобы не создавать еще один фикс-скрипт?

2024-01-15 06:43 UTC, egorchh commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.module.scss
> +.NewTopicForm {
[не крит] Может быть для единообразия с мои залитым МР будем использовать `camelCase` вместо `PascalCase`? Нужно договориться на что-то одно

В контексте css-modules можем писать нейминг стилей проще: вместо NewTopicForm - form. Они все равно будут уникальны

2024-01-15 06:43 UTC, egorchh commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +	onClick(): void;
Тип onClick должен быть: `() => void`; Но для таких случаев есть тип `VoidFunction`

2024-01-15 06:53 UTC, pira9ha commented on packages/client/package.json
> +    "classnames": "^2.5.1",
classnames лучше использовать готовый, она не настолько тяжелая)

2024-01-15 06:53 UTC, pira9ha commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +	onClick(): void;
а чем такое описание типа плохо?

2024-01-15 06:58 UTC, pira9ha commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.module.scss
> +.NewTopicForm {
camelCase ок)

2024-01-15 17:36 UTC, egorchh commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +	onClick(): void;
Сори, я не увидел скобки в конце`onClick()`, впервые такую запись встречаю если честно. Прикольно

2024-01-15 17:37 UTC, egorchh commented on packages/client/package.json
> +    "classnames": "^2.5.1",
Почему лучше готовый?

2024-01-15 18:27 UTC, egorchh commented on packages/client/src/Pages/Topic/components/SmileMenu/SmileMenu.svg
> +<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Можно сжать свгэшку и выиграть несколько килобайт. Например, через сервис https://svgomg.net/

2024-01-15 18:27 UTC, egorchh commented on packages/client/src/Pages/Topic/components/SmileMenu/SmileMenu.tsx
> +			<button className={s.SmileMenuButton} onClick={handlerMenuOpen}>
Почему в этом файде <button> используется, а не компонент Button из @components

2024-01-15 18:27 UTC, egorchh commented on packages/client/src/components/Input/index.tsx
> +	const InputTag = useMemo(() => {
Вычисление не тяжелое, мне кажется в таких случаях лучше не юзать мемоизацию. Больше памяти потратится чем будет профита. Как думаешь?

2024-01-15 18:27 UTC, egorchh commented on packages/client/src/components/Link/index.tsx
> +	const createPath = () => {
А для чего махинации с компонентом ссылки? Нам же все равно придется заиспользовать Link из роутер-дома?

2024-01-15 18:38 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						href={path}
Кажется функциональность поломана. Сейчас ведь не будет работать нажатие кнопки Enter из-за того, что ref не передан?

2024-01-15 18:38 UTC, egorchh commented on packages/client/src/utils/abbreviateNumber.ts
> +			if (number === 1000 && i < abbrev.length - 1) {
Тут константу `abbreviateThreshold` нужно кажется вставить

2024-01-15 18:38 UTC, egorchh commented on packages/client/src/utils/abbreviateNumber.ts
> +			if (number === 1000 && i < abbrev.length - 1) {
Эта функция используется для отображения кол-ва комментариев в удобочитаемом формате?

2024-01-15 19:38 UTC, pira9ha commented on packages/client/src/Pages/Forum/index.tsx
> +	const handleOpenTopicCreator = () => {
Или использует стейт внутри) но мы на работе постоянно оборачиваем для дополнительной мемоизации, оно скорее всего прям сильно ниче не меняет, но это у меня на автомате уже😅

2024-01-15 19:39 UTC, pira9ha commented on packages/client/src/Pages/Forum/lib/constants.ts
Норм идея, свои тада заодно перекину, если мр ещё не вмерджил, а то потом забудется)

2024-01-15 19:41 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/Comment/Comment.tsx
> +type CommentProps = IComment;
Тип пропсов тут на уровне компонента и лежит) Алиас нужен, потому что мне так нравится ибо пропсы это все таки не модель данных) но тк оно совпадает так и сделал, все таки корректный нейминг для всего это полезная привычка + есть простор для расширения типа пропсов😅 а тут интерфейс это модель коммента

2024-01-15 19:42 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/SmileMenu/SmileMenu.svg
> +<svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Прикольно, спасибо)

2024-01-15 19:43 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/SmileMenu/SmileMenu.tsx
> +			<button className={s.SmileMenuButton} onClick={handlerMenuOpen}>
Не додумалась так расширить компонент, исправлю, только когда ты написал😅

2024-01-15 19:44 UTC, pira9ha commented on packages/client/src/components/Input/index.tsx
> +	const InputTag = useMemo(() => {
Думаю ты прав, надо перепроверить посмотрю поправлю)

2024-01-15 19:47 UTC, pira9ha commented on packages/client/src/components/Link/index.tsx
> +	const createPath = () => {
Могу вернуть, но тег все-таки использую <a> и прикола forwardRef тут вообще не вижу, зачем? пропсы тоже изменятся во всех случаях, так что наверное было лень исправлять свой код)
Что думаешь?

2024-01-15 19:49 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						href={path}
Если использовать семантический тег ссылки, то должно работать, если ты об этом

2024-01-15 19:50 UTC, pira9ha commented on packages/client/src/utils/abbreviateNumber.ts
> +			if (number === 1000 && i < abbrev.length - 1) {
Да, типа 1К комментов и более, потому что с слишком длинно полностью писать (фантазируем огромную популярность нашей игры😂)

2024-01-15 19:52 UTC, pira9ha commented on packages/client/package.json
> +    "classnames": "^2.5.1",
Да, но тут это библиотека, немного другое, вычисления будут и так и так, там где функция вызывпется, ребята, кто ещё что думает? Я просто за то, что проверено, тыщу раз протестировано и популярно, вместо своих велосипедов

2024-01-15 19:53 UTC, pira9ha commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +	onClick(): void;
Та ничего, твоё мнение просто было интересно узнать что ж не так с типом😁 я просто обе записи встречаю и думала, что может есть какие-то правила

2024-01-15 19:56 UTC, alexdx0 commented on packages/client/package.json
> +    "classnames": "^2.5.1",
лучше clsx

2024-01-15 19:58 UTC, pira9ha commented on packages/client/package.json
> +    "classnames": "^2.5.1",
Почему? Не знакома с либой, есть лично у тебя интересные статьи о ней?

2024-01-15 19:59 UTC, alexdx0 commented on packages/client/src/Pages/Forum/index.tsx
> +	const handleOpenTopicCreator = () => {
там тогда и memo нужен

2024-01-15 20:06 UTC, pira9ha commented
Могу опечататься и не заметить, если непонятно, то переспрашивайте пожалуйста😊

2024-01-15 20:08 UTC, alexdx0 commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						onClick={action ? onExit : undefined}
что-то с отступами все равно беда...

2024-01-15 20:10 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						onClick={action ? onExit : undefined}
Я вроде не меняла( tab на 2

2024-01-15 20:10 UTC, egorchh commented on packages/client/package.json
> +    "classnames": "^2.5.1",
Все эти либы обладают идентичной функциональностью. Понимаю, что всем хочется оставить свое) Давайте тогда classNames, чтобы не разводить спор. Сможешь тогда заменить везде мой classnames на либу?

2024-01-15 20:10 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						onClick={action ? onExit : undefined}
Пересмотрю что можно сделать👌

2024-01-15 20:12 UTC, pira9ha commented on packages/client/package.json
> +    "classnames": "^2.5.1",
Может ещё мнение услышим и решим методом большинства?

2024-01-15 20:16 UTC, egorchh commented on packages/client/src/Pages/Forum/index.tsx
> +	const handleOpenTopicCreator = () => {
memo можно заюзать, чтобы ForumPage не перерендеривался при перерендере роутера, кажется

2024-01-15 20:24 UTC, pira9ha commented on packages/client/src/Pages/Forum/index.tsx
> +	const handleOpenTopicCreator = () => {
Топик это отдельная страница, а если чисто комментов меняться будет, то это можно тогда в компоненте Comment использовать чтобы страница вся не менялась

2024-01-15 20:27 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/Comment/Comment.tsx
> +type CommentProps = IComment;
Явная типизация пропсов, лучше не явной, а интерфейс будет юзаться ещё в других местах, поэтому конкретно этот интерфейс не тип пропсов - так что алиас на пропсы нужен, вот если перефразировать

2024-01-15 20:55 UTC, egorchh commented on packages/client/src/Pages/Topic/components/Comment/Comment.tsx
> +type CommentProps = IComment;
Так понятнее, спасибо, полностью согласен

2024-01-15 20:58 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						href={path}
хмм, даже не знаю если честно, проверим как появится роутер 🐞

2024-01-15 20:58 UTC, egorchh commented on packages/client/src/utils/abbreviateNumber.ts
> +			if (number === 1000 && i < abbrev.length - 1) {
Ахаха, так она и будет популярной!

2024-01-15 21:01 UTC, egorchh commented on packages/client/src/components/Link/index.tsx
> +	const createPath = () => {
Я тут forwardRef использовал как раз для того, чтобы иметь возможность использовать метод onClick дочернего компонента в родительском компоненте. Но ты права, наверное, когда тут будет компонент Link из router-dom, нажатие по Enter будет срабатывать нативно без всяких рефов

2024-01-15 21:02 UTC, egorchh approved these changes

2024-01-15 21:22 UTC, VasiliiOrekhov commented on packages/client/package.json
> +    "classnames": "^2.5.1",
я за classnames из utils, функционал там не сложный, необходимости в библиотеке не вижу

2024-01-15 21:24 UTC, IpratchetI approved these changes

2024-01-15 21:29 UTC, IpratchetI commented
конфликты разрешить нужно

2024-01-15 21:39 UTC, VasiliiOrekhov approved these changes

2024-01-15 21:50 UTC, pira9ha commented
> конфликты разрешить нужно

Это и так очевидно🤔

2024-01-16 20:11 UTC, VasiliiOrekhov commented on packages/client/src/Pages/Forum/components/TopicsList/TopicsList.module.scss
> +  grid-template-columns: calc(2 / 3 * 1fr) calc(1 / 3 * 1fr);
можно сделать проще:
```suggestion
  grid-template-columns: 2fr 1fr;
```

2024-01-16 20:54 UTC, VasiliiOrekhov requested changes

2024-01-16 20:54 UTC, VasiliiOrekhov commented on packages/client/src/Pages/Forum/components/TopicsList/TopicsList.tsx
> +							href={`/forum/${topic.id}`}
хардкод роутов предлагаю вынести в константы

2024-01-16 20:54 UTC, VasiliiOrekhov commented on packages/client/src/Pages/Topic/components/Comment/Comment.tsx
> +import { CURRENT_USER_ID, USERS } from '../../lib/constants';
проверь мб стоит расширить именованные импорты

2024-01-16 20:54 UTC, VasiliiOrekhov commented on packages/client/src/Pages/Topic/components/MessageForm/MessageForm.tsx
> +				onKeyPress={handleUserKeyPress}
'onKeyPress' is deprecated.ts(6385)
метод помечен как deprecated
лучше заменить на onChange формы и отказаться от ref

2024-01-16 21:03 UTC, pira9ha commented on packages/client/src/Pages/Forum/components/TopicsList/TopicsList.tsx
> +							href={`/forum/${topic.id}`}
Предлагаю вынести их в один файл в задаче с добавлением роутера

2024-01-16 21:04 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/Comment/Comment.tsx
> +import { CURRENT_USER_ID, USERS } from '../../lib/constants';
Можно поконкретнее, пожалуйста?)

2024-01-16 21:06 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/MessageForm/MessageForm.tsx
> +				onKeyPress={handleUserKeyPress}
Реф тут отношение к событию никакого не имеет) Пока не вижу причины  и аргумента его убирать, поэтому оставляю, тк он нужен там, где он используется

2024-01-16 22:57 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +						onClick={action ? onExit : undefined}
@alexdx0 [вот тут](https://docs.github.com/ru/enterprise-cloud@latest/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-user-account-settings/managing-your-tab-size-rendering-preference) описано как настроить отображение табов на гитхабе)

2024-01-16 23:01 UTC, pira9ha commented on packages/client/package.json
> +    "classnames": "^2.5.1",
библиотека дает возможность не писать лишнего типа вот:
<img width="416" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/d9155b4e-54a8-44e6-a4bd-099a30ee2445">
<img width="557" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/fccb6d1b-c203-4d23-a4e0-1c9d4d7197db">

Мне не совсем нравится писать сверх, поэтому считаю плюсом либы, но если смущает только меня, то ок

2024-01-16 23:10 UTC, pira9ha commented on packages/client/src/Pages/Topic/components/MessageForm/MessageForm.tsx
> +				onKeyPress={handleUserKeyPress}
Сменила на onKeyDown

2024-01-17 06:52 UTC, alexdx0 requested changes

2024-01-17 06:52 UTC, alexdx0 commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +export const NewTopicForm = ({ onClick }: NewTopicFormProps) => {
Компоненты решили писать в index-файлах, без public api. Так же это позволяет избежать дублирование имени (папка/файл) при импорте. Предлагаю везде делать единообразно.

2024-01-17 09:16 UTC, pira9ha commented on packages/client/src/Pages/Forum/components/NewTopicForm/NewTopicForm.tsx
> +export const NewTopicForm = ({ onClick }: NewTopicFormProps) => {
Так тут и нет паблик апи, это файлы внутри одной дериктории и компоненты тоже, их импорт в родительский компонент
Ок, переименую

2024-01-17 09:42 UTC, pira9ha commented on packages/client/src/components/Input/lib/useTextarea.tsx
> +			textareaRef.current.style.height = textareaRef.current.scrollHeight + 'px';
Затем, чтобы при увеличении размера он не оставался максимальным
<img width="1123" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/9c3fe357-9ff3-4169-b846-2c90f26f55a6">

2024-01-17 16:28 UTC, alexdx0 commented on packages/client/src/components/Input/lib/useTextarea.tsx
> +			textareaRef.current.style.height = textareaRef.current.scrollHeight + 'px';
Супер, спасибо.

2024-01-17 16:31 UTC, alexdx0 approved these changes

2024-01-17 18:31 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечаний
Поздравляю, апрув 🚀

2024-01-18 19:05 UTC, VasiliiOrekhov approved these changes

2024-01-18 21:46 UTC, merged