Gal 13 main page layout
IpratchetI/galaxy_conquerors pull request #6
Opened 2024-01-13 09:03 UTC by egorchh

### Какую задачу решаем
Создаем главную страницу приложения. Главная страница представляет из себя заголовок сайта и навигационная панель по сайту с ссылками на другие экраны

Помимо главной страницы были добавлены ui-компоненты: Spacer, Text, Button (wip), Link (wip).

### Скриншоты/видяшка (если есть)
<img width="1721" alt="Screenshot 2024-01-13 at 12 01 40" src="https://github.com/IpratchetI/galaxy_conquerors/assets/93445522/a3924141-ce40-4e5c-911a-43954010de94">

### TBD (если есть)

2024-01-13 12:29 UTC, pira9ha commented on packages/client/src/components/Link/index.tsx
> +		}
Ссылка это ссылка, если нужна кнопка, то пропиши в ней вариативность стилей, если надо

2024-01-13 12:48 UTC, pira9ha commented on packages/client/src/components/Text/index.tsx
> +})
У нас был пример типа такого использования, хотя использовать dangerouslySetInnerHTML излишне, все-таки вариант передавать текст как children: ReactNode лучше, если прям жизненно необходимо ставить br, но и это можно обойти заюзав \n  в тексте и в css прописать white-space: pre-line;

но это все имхо

<img width="531" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/819c7955-8421-4458-a61f-5bb893cb4e53">

2024-01-13 12:49 UTC, pira9ha commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Это можно прописать стилями (миксинами например), как будто слегка излишне

2024-01-13 12:53 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
А зачем так делаешь?

2024-01-13 12:55 UTC, pira9ha commented on packages/client/src/style/variables.scss
> +:root {
В итоге используем переменные через рут? Надо было тогда в предыдущем МР так и прописать, не совсем понимаю тогда предыдущих действий с общими стилями)

2024-01-13 13:01 UTC, pira9ha commented on .eslintrc.js
> +    'object-curly-spacing': [ 'error', 'always' ],
comma-dangle мне лично нравится, это удобно
Вообще вроде обговаривали использовать какие-то дефолтные или общие правила, поправьте, если не права, просто кмк лучше тогда обсудить что добавляем, а что нет

Не коммент на фикс, просто предложение

2024-01-13 13:05 UTC, pira9ha commented on packages/client/src/components/Button/index.tsx
> +} & ButtonHTMLAttributes<HTMLButtonElement>
У пропсов кнопки и так есть, не вижу смысла его переписывать
<img width="726" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/95795b6c-6005-44f5-a19c-8786d34fe4bd">

2024-01-13 13:09 UTC, IpratchetI commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Согласен

2024-01-13 13:11 UTC, egorchh commented on .eslintrc.js
> +    'object-curly-spacing': [ 'error', 'always' ],
А мне не нравится, но готов подстроиться

2024-01-13 13:13 UTC, egorchh commented on packages/client/src/style/variables.scss
> +:root {
В ходе разработки решил что так будет удобней, оставил предыдущий вариант в коде тоже. Такой подход позволяет не импортировать миксины в каждый стилевой файл, поскольку мы работаем с css модулями. Если не прав, поправь

2024-01-13 13:13 UTC, pira9ha commented on .eslintrc.js
> +    'object-curly-spacing': [ 'error', 'always' ],
Поэтому я и предлагала это обсудить ранее, менять что-то не призываю)

2024-01-13 13:14 UTC, pira9ha commented on packages/client/src/style/variables.scss
> +:root {
Не, я наоборот за, мне так больше нравится и более привычно)

2024-01-13 13:14 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Чтобы не дублировать код для каждой ссылки.  + Мне кажется, так будет проще править контент ссылок, просто меняя данные в массиве navLinks вверху

2024-01-13 13:16 UTC, IpratchetI commented on packages/client/src/App.tsx
как бы у нас потом с регистрами проблем не возникло. В нейминге файлов и папок, это очень бросается в глаза. нужно придти к общему мнению - либо мы пишем наименования с маленькой буквы, либо с заглавной.

2024-01-13 13:16 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Так не дублируй, это же происходит в цикле, этот кусок кода достаточно скопировать-вставить и будет то, же
Зачем нужны рефы сейчас на активные ссылки? Мне кажется просто навесить стиль на активную более чем достаточно

2024-01-13 13:17 UTC, egorchh commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
имхо, использовать ХОК для таких целей более удобно. + Хотел потренироваться в написании ХОКов

2024-01-13 13:18 UTC, pira9ha commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Тянешь лишние вычисления там, где они не излишни

2024-01-13 13:19 UTC, IpratchetI commented on packages/client/src/components/Link/index.tsx
> +		}
зачем нам ссылки в мейне? давайте все таки использовать button

2024-01-13 13:21 UTC, IpratchetI commented on packages/client/src/components/Spacer/index.module.scss
очень громоздко получается. Предложение пересмотреть структуру, но можем на потом это оставить

2024-01-13 13:22 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Вот прям не вижу причин так делать, просто объясните
У тебя массив ссылок, все данные там в NavLink, это массив и не более, что ты там менять не сможешь не понятно, тк компонент от этого сейчас не зависит тк ты снаружи берешь данные, а внутри вариативности кроме как isActive нет
Извини за духоту, если что, мне важно самой понять смысл использования useCallback, как минимум useMemo было бы логичнее, но зачем, у тебя все в memo обернуто

2024-01-13 13:23 UTC, egorchh commented on packages/client/src/components/Text/index.tsx
> +})
dangerouslySetInnerHTML использовать опасно, а вот использовать \n и white-space: pre-line не додумался. Исправлю, спасибо!

2024-01-13 13:23 UTC, pira9ha commented on packages/client/src/components/Spacer/index.module.scss
Согласна

2024-01-13 13:23 UTC, IpratchetI commented on packages/client/src/components/Text/index.module.scss
.s {
  font-size: var(--font-size-20);
}

.m {
  font-size: var(--font-size-30);
}

может тоже нейминг поменять, чтобы более понятно было? 
так например
.m-size {
  font-size: var(--font-size-30);
}

2024-01-13 13:24 UTC, pira9ha commented on packages/client/src/components/Link/index.tsx
> +		}
Если ты делаешь компонент Link то это и должна быть ссылка, а как только ты добавишь роутер, то навигация должна быть через роутеровский нативный Link

2024-01-13 13:26 UTC, IpratchetI commented on packages/client/src/pages/test
этот файл удалить вообще нужно

2024-01-13 13:27 UTC, pira9ha commented
Константные и моковые значения лучше хранить отдельно

2024-01-13 13:28 UTC, pira9ha commented on packages/client/src/components/Text/index.tsx
> +})
Это как один из вариантов, не за что) не забудь протестить нужное ли поведение получишь)

2024-01-13 13:28 UTC, IpratchetI commented on packages/client/src/utils/test
тоже удалить.

2024-01-13 13:30 UTC, pira9ha commented on packages/server/db.ts
> +		})
У всех в ide могут быть разные настройки отступов, надо на препуш фиксить и к единому приводить, чтобы такие файлы не попадали в МР

2024-01-13 13:30 UTC, egorchh commented on packages/client/src/components/Link/index.tsx
> +		}
Этот компонент как раз и будет содержать Link из роутер-дома после его добавления в проект. Про то что ссылка должна быть ссылкой, а кнопку перенести в отдельный компонент - согласен, поправлю

2024-01-13 13:31 UTC, IpratchetI requested changes
посмотри ошибку по линтеру в гите

2024-01-13 13:33 UTC, pira9ha commented on packages/client/src/components/Link/index.tsx
> +		}
@egorchh  я понимаю, что это будет роутеровская линка, ты же тудушку оставил) второй коммент @IpratchetI больше был адресован)

2024-01-13 13:51 UTC, egorchh commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Приложению практически ничего не стоит обернуть компонент в HOC, предлагаю оставить так

2024-01-13 13:53 UTC, egorchh commented on packages/client/src/components/Text/index.module.scss
Обычно буквами s, m, l и так далее только размеры обозначаются

2024-01-13 13:57 UTC, egorchh commented on packages/client/src/components/Spacer/index.module.scss
Не вижу в этом проблемы, компонент не рассчитан на постоянную работу с ним. Один раз написал и забыл. Зато его использование позволяет не писать каждый раз дефолтные стили для расположения компонентов

2024-01-13 14:07 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Давай еще раз, в чем изначальный вопрос был?

2024-01-13 14:11 UTC, egorchh commented on packages/client/src/App.tsx
App.tsx исправлю на маленькую букву

2024-01-13 14:13 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
А зачем так делаешь? Какой смысл?

2024-01-13 14:15 UTC, pira9ha commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Практически ничего не стоит - копится и плохо влияет на производительность, одно допущение тут, одно там и тд

2024-01-13 14:15 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Как делаю? О чем конкретно речь?

2024-01-13 14:23 UTC, pira9ha reviewed
Какие-то моменты исправить или пояснить

2024-01-13 15:08 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Изначально неправильно понял вопрос, cейчас гуд! По поводу useCallback согласен, что он тут бесполезен, тогда вынесу маппинг в jsx разметку. Без дополнительной функции. 

Я супер слаб в мемоизации. В целом тут можно и в memo не оборачивать так как нет пропсов от родителя?

2024-01-13 15:13 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
Ну я местами тоже могу упускать мемоизацию, в конкретно этом компоненте memo ничего не решает, у него нет пропсов, меняется только внутренний стейт поэтому перерендериваться все равно будет так же как и без мемо)

2024-01-13 15:15 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +	)
можно вот тут почитать и самому сделать выводу, но не верить одной сомнительной разработчице) [дока](https://react.dev/reference/react/memo) [хабр](https://habr.com/ru/articles/706730/)

2024-01-13 16:10 UTC, egorchh commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
А мне так нравился подход с HOC 😢

2024-01-13 16:12 UTC, pira9ha commented on packages/client/src/hocs/withBackground/index.tsx
> +		)
Да заюзаешь еще, там стока задач😅

2024-01-13 20:10 UTC, IpratchetI commented on packages/client/src/components/Text/index.module.scss
ну это было предложение, не более, в целом не имеет особого значения=)

2024-01-13 20:24 UTC, IpratchetI approved these changes

2024-01-13 21:59 UTC, pira9ha approved these changes

2024-01-14 08:35 UTC, VasiliiOrekhov approved these changes

2024-01-14 11:11 UTC, alexdx0 commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +					<li key={id}>
Настроенные размеры отступов кажутся очень большими. При большей вложенности всё сильно уедет. Понятно, что IDE отобразит красиво, но исходники в гитхабе просматривать будет очень неудобно.

2024-01-14 11:19 UTC, alexdx0 commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +					<li key={id}>
Предлагаю такой конфиг по отступам:
indent_style = space
indent_size = 2

2024-01-14 11:22 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +					<li key={id}>
Предлагаю все-таки tab на 2

2024-01-14 11:23 UTC, pira9ha commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +					<li key={id}>
https://www.youtube.com/watch?v=AXLoRpKnK8U&ab_channel=ArsSazary

2024-01-14 11:42 UTC, egorchh commented on packages/client/src/pages/Main/components/LinksList/index.tsx
> +					<li key={id}>
Да окей, гитхаб что-то не вывозит ширину 4

2024-01-14 12:25 UTC, alexdx0 approved these changes

2024-01-14 12:48 UTC, merged