GAL-14 Create universal component ErrorPage
IpratchetI/galaxy_conquerors pull request #7
Opened 2024-01-14 14:08 UTC by egorchh

### Какую задачу решаем

Создал компонент страницы ошибки. Компонент принимает на вход пропс type={'404' | '500'}, по которому определяет содержание страницы.
Предлагаю немного изменить макет и использовать текст 'go to main' вместо кнопки 'main' как в оригинальном макете. Это позволит использовать уже готовый компонент Link без раздувания дополнительными стилями

### Скриншоты/видяшка (если есть)

<img width="1724" alt="Screenshot 2024-01-14 at 17 06 22" src="https://github.com/IpratchetI/galaxy_conquerors/assets/93445522/cbbbc305-876c-4e15-a411-910fdb1fd354">
<img width="1723" alt="Screenshot 2024-01-14 at 17 06 31" src="https://github.com/IpratchetI/galaxy_conquerors/assets/93445522/e37f175c-2ae8-4af3-a95e-1e263f56f35c">

### TBD (если есть)

2024-01-14 14:59 UTC, pira9ha requested changes

2024-01-14 14:59 UTC, pira9ha commented on packages/client/src/style/backgrounds.scss
> +  background-size: cover;
background-size: cover; и background-repeat: no-repeat; можно прописать только в одном месте, а картинки уже все разные, у нас бэкграунд вроде весте ж растянут на страницах

2024-01-14 15:01 UTC, pira9ha commented
Не совсем поняла про текст в кнопке, потому что готовый компонент как с этим связан?

2024-01-14 15:10 UTC, IpratchetI commented on packages/client/src/pages/Error/index.tsx
может кнопкой сделаем вместо линка? чтобы не плодить компоненты?

2024-01-14 15:20 UTC, egorchh commented on packages/client/src/pages/Error/index.tsx
У нас есть компонент Link в котором будет Link из react-router-dom. На этой странице при нажатии на go to main мы как раз должны перемещаться по роуту. То есть должен использоваться наш компонент Link по логике. Но в макете сейчас явно нарисована кнопка. Есть 3 варианта:

1. Перерисовать макет так, чтобы тут консистентно подходил готовый комопонент Link
2. Дополнить пропсы компонента Link таким образом, чтобы при передаче пропса он менял свой стиль на точно такой же как будет у компонента Button.
3. Расширить функционал компонента Button, чтобы он также умел редиректить по линку из роутера

Третий вариант точно нет, потому что кнопка должна всегда оставаться кнопкой, ей незачем иметь функциональность редиректа. Второй вариант раздувает компонент ненужной логикой и стилями. Выбрал первый вариант. Такой подход как раз предотвращает появление новых компонентов

2024-01-14 15:21 UTC, egorchh commented on packages/client/src/pages/Error/index.tsx
Мы тут не можем заюзать кнопку потому что по логике это ссылка-редирект на мейнъ

2024-01-14 15:26 UTC, pira9ha commented on packages/client/src/pages/Error/index.tsx
Тут согласна с @IpratchetI, потому что навигация назад скорее осуществляетсмя через useNavigate() navigate(-1) поэтому это логичнее запихнуть в onClick кнопки, потому что в теории на слик можно навесить чистку стейта и подобное

2024-01-14 15:27 UTC, pira9ha commented on packages/client/src/pages/Error/index.tsx
и не надо расширять функционал кнопки, либа компонентов должна быть условно абстрактной и не зависеть от внешних реализаций

2024-01-14 15:28 UTC, pira9ha commented on packages/client/src/pages/Error/index.tsx
т.е. кнопка и ссылка не знают про бизнес логику, им вообще плевать как у нас все реализовано, поэтому они должны быть достаточно расширяемыми и переиспользуемыми, легкими желательно, особенно если говорим про наш проект, это как типа если бы ты эти компоненты подключил из бутстрапа или анта

2024-01-14 15:36 UTC, egorchh commented on packages/client/src/pages/Error/index.tsx
Хорошо, так можно согласен. Но не вижу проблемы в использовании Link. Или мы дорожим изначальной версией дизайна? Зачем нам чистить стейт возвращаясь с ошибочной страницы на main? На этот случай, на Link из роутер-дома тоже можно навесить onClick

2024-01-14 15:55 UTC, pira9ha commented on packages/client/src/pages/Error/index.tsx
что делать вот с такими кнопками? поменять дизайн? если хочешь где-то в одном менять, тогда надо и везде, я просто не поняла причем тут компонент вообще
<img width="189" alt="image" src="https://github.com/IpratchetI/galaxy_conquerors/assets/67172139/4aa44788-dc65-4c2f-8f3e-7f390ab0a048">

2024-01-14 16:24 UTC, alexdx0 approved these changes

2024-01-15 06:21 UTC, egorchh commented on packages/client/src/pages/Error/index.tsx
Нет, они пусть остаются, просто конкретно в этом месте мне показалось что лучше заиспользовать ссылку, а не кнопку. Поэтому изменил дизайн

2024-01-15 17:49 UTC, IpratchetI approved these changes

2024-01-15 18:12 UTC, VasiliiOrekhov approved these changes

2024-01-15 19:27 UTC, merged